# Generated by Django 5.0.4 on 2024-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_subscribtion_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe ID'),
        ),
    ]
